name: Checks

on:
  push:
    branches: [main]
    paths:
      - charmcraft.yaml
      - requirements.txt
      - test-requirements.txt
      - tox.ini
      - lib/**
      - src/**
      - tests/**
  pull_request:
    paths:
      - charmcraft.yaml
      - requirements.txt
      - test-requirements.txt
      - tox.ini
      - lib/**
      - src/**
      - tests/**
  # NOTE: run the workflow every friday at midnight to catch breaking
  # changes in both the environment and external dependencies
  schedule:
    - cron: '0 0 * * 5'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linters
        run: uvx tox run -e lint
  unit:
    name: Unit test
    runs-on: ubuntu
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: uvx tox run -e unit
  static:
    name: Static type check
    runs-on: ubuntu
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run static type checking
        run: uvx tox run -e static

  integration:
    name: Integration test
    runs-on: ubuntu
    timeout-minutes: 180
    needs: [lint, unit, static]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pack charm
        id: pack
        # NOTE: since our runners are ephemeral, we can use the --destructive-mode
        # flag. Despite the spooky name, the only implication of this is that the
        # packing will occur on the local system, instead of spawning a new LXC
        # container to perform this operation, which is the default behavior.
        run: sudo charmcraft pack --destructive-mode
      - name: Move charm to directory
        run: mkdir -p charm && mv *.charm charm
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          bootstrap-constraints: cores=2 mem=2G virt-type=virtual-machine
      - name: Run integration tests
        run: uvx tox run -e integration
