name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - '.jujuignore'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - '.jujuignore'
      - 'LICENSE'
      - '**.md'
  # NOTE: run the workflow every day at midnight to catch breaking
  # changes in both the environment and external dependencies
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint charm
    runs-on: ubuntu
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linters
        run: uvx tox run -e lint
  unit:
    name: Unit test charm
    runs-on: ubuntu
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: uvx tox run -e unit
  static:
    name: Static type check charm
    runs-on: ubuntu
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run static type checking
        run: uvx tox run -e static
  build:
    name: Build charm
    runs-on: ubuntu
    timeout-minutes: 10
    needs: [lint, unit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pack charm
        id: pack
        # NOTE: since our runners are ephemeral, we can use the --destructive-mode
        # flag. Despite the spooky name, the only implication of this is that the
        # packing will occur on the local system, instead of spawning a new LXC
        # container to perform this operation, which is the default behavior.
        run: sudo charmcraft pack --destructive-mode
      - name: Upload charmcraft logs
        if: ${{ failure() && steps.pack.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-charmcraft-build-${{ github.run_id }}
          path: ~/.local/state/charmcraft/log/
          if-no-files-found: error
      - name: Upload charm package
        uses: actions/upload-artifact@v4
        with:
          name: charm-incus-${{ github.run_id }}
          path: |
            *.charm
          if-no-files-found: error
