name: Documentation Checks

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  spellcheck:
    name: Spellcheck Markdown Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.46.0
        with:
          task_name: Markdown

  linkcheck:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
